### ISSUE TITLE
Edited or deleted messages are still shown with the original content when quoted in other rooms

### ISSUE THREAD

**Issue by ssoflashy** [skychatorg/skychat#138]
When someone post a message, edit or delete it, it stills can be seen if someone quote it in another room:
Message posted :
![image](https://user-images.githubusercontent.com/17952985/153223287-e69d7a8d-bc4e-4566-b2ee-ea86fc443f78.png)
Message deleted :
![image](https://user-images.githubusercontent.com/17952985/153223446-72bc8884-8d25-494c-ad9e-c24d18c67c9a.png)
Original message quoted :
![image](https://user-images.githubusercontent.com/17952985/153223592-d88b6921-10f2-41c3-a13d-ad51ab1b6d84.png)

**Comment by 7PH** [comment]
Fixed by https://github.com/skychatorg/skychat/commit/1e4c2811279cf08d301dedb3badbd1b7cd37b7d1
