### ISSUE TITLE
Create event for money payment

### ISSUE THREAD

**Issue by ssoflashy** [skychatorg/skychat#21]
Currently when someone pays another person with skypoints, there is no dedicated event.
An event with the person sending, receiving, the money sent and the commission as attributes would be very convenient.

**Comment by 7PH** [comment]
I agree. I think this custom event should replace the message currently sent to the sender+receiver here: https://github.com/skychatorg/skychat/blob/master/app/server/skychat/commands/impl/core/GiveMoneyPlugin.ts#L58

Are you suggesting that the event is sent not only to the sender+receiver but to everyone in the room? Do you have any use case for that? I'm not against.

**Comment by 7PH** [comment]
@Sn4ily @ogbaba @k8th

**Comment by Kardygan** [comment]
I agree. It will be useful for bots I suppose.
