### ISSUE TITLE
Autocomplete stickers in the message input

### ISSUE THREAD

**Issue by Kardygan** [skychatorg/skychat#74]
A feature to show corresponding stickers when you type the two or three first letters of their codes. Useful feature for newcomers and regulars to discover or to see some forgotten stickers. 

Here is an example from Discord App : 
![discord](https://user-images.githubusercontent.com/63365690/95797238-476d6200-0cef-11eb-9a84-3c3b6db03f1f.png)

**Comment by 7PH** [comment]
Love it. But I'm not that familiar with autocomplete libraries, we need to find a lightweight one which suits our needs. I'll take a look.
It may also be the case that we want to implement a custom one.

**Comment by 7PH** [comment]
Added in https://github.com/skychatorg/skychat/pull/178
