### ISSUE TITLE
Rework colors shop

### ISSUE THREAD

**Issue by Kardygan** [skychatorg/skychat#85]
At the moment, the colors shop takes a lot of space in the chatbox. I think the list is too long, it breaks the flow and there are redundant information (nickname, prices, buy and set buttons). Here is an idea to improve it : 

![19-12-39-93091776](https://user-images.githubusercontent.com/63365690/98286601-87e59600-1fa4-11eb-86cf-9287ce72de18.png)

It would be great to create a new small panel at the bottom in the right column that only appears when you click on the "Color" button. In my opinion, color squares provide a better view as color samples. When you click on one of those, the name, the preview and the price could change dynamically with matching information. 

No more overloaded chatbox and redundant information. It's compact and clear for the user.

**Additional info & suggestions**:
* 3 ways to close the panel 
1) Click again on the "Color" button
2) Add a small X icon in the corner
3) (When you have set a color ?)
* Color squares size is 16x16 pixels in the picture and the space between them is 6px
* Buy button could be closer to the price for better coherence ?
* I have put a border around the selected color but I'm not satisfied with the look of it. All ideas are welcome.

**Comment by 7PH** [comment]
done
![image](https://user-images.githubusercontent.com/31401273/177216868-32e07778-2ae0-4e51-b30c-7874d23af9c1.png)
